# Generated by Django 4.2.4 on 2023-08-18 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.TextField(default="미입력", verbose_name="연락처")),
                ("name", models.TextField(default="미입력", verbose_name="이름")),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("dog", "개"), ("cat", "고양이"), ("etc", "기타")],
                        default="미확인",
                        max_length=10,
                        verbose_name="동물",
                    ),
                ),
                (
                    "kind",
                    models.CharField(default="미확인", max_length=15, verbose_name="품종"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("암컷", "암컷"), ("수컷", "수컷")],
                        default="미확인",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "is_neutered",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("중성화O", "중성화O"), ("중성화X", "중성화X")],
                        default="미확인",
                        max_length=11,
                        verbose_name="중성화",
                    ),
                ),
                (
                    "age",
                    models.CharField(default="미확인", max_length=10, verbose_name="나이"),
                ),
                (
                    "weight",
                    models.CharField(default="미확인", max_length=10, verbose_name="몸무게"),
                ),
                (
                    "reason",
                    models.CharField(default="미입력", max_length=20, verbose_name="사유"),
                ),
                ("title", models.CharField(max_length=20, verbose_name="제목")),
                ("content", models.CharField(max_length=70, verbose_name="내용")),
                ("alert", models.TextField(default="특이사항 없음", verbose_name="특이사항")),
                ("condition", models.TextField(default="임보조건 없음", verbose_name="임보조건")),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="사진"),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="사진"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="작성일"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
