# Generated by Django 4.2.4 on 2023-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="address",),
        migrations.AddField(
            model_name="user",
            name="address1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="address2",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
