# Generated by Django 4.2.4 on 2023-08-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_address_user_address1_user_address2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, upload_to="uploaded_pictures", verbose_name="프로필"
            ),
        ),
    ]
