# Generated by Django 4.2.4 on 2023-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, upload_to="", verbose_name="프로필"),
        ),
    ]
