# Generated by Django 4.2.4 on 2023-08-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_profile"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="users",),
    ]
