# Generated by Django 4.2.4 on 2023-08-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, upload_to="profiles/", verbose_name="프로필"
            ),
        ),
    ]
