# Generated by Django 4.2.4 on 2023-08-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='공고동물 이름')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='공고동물 사진')),
                ('gender', models.CharField(choices=[('unknown', '미확인'), ('female', '암컷'), ('male', '수컷')], default='unknown', max_length=10, verbose_name='성별')),
                ('is_neutered', models.CharField(choices=[('unknown', '미확인'), ('neutered', '중성화O'), ('notneutered', '중성화X')], default='unknown', max_length=11, verbose_name='중성화 여부')),
                ('age', models.CharField(default='미확인', max_length=10, verbose_name='나이')),
                ('weight', models.CharField(default='미확인', max_length=10, verbose_name='몸무게')),
                ('content', models.CharField(max_length=70, null=True, verbose_name='관리자 한마디')),
                ('alert', models.TextField(null=True, verbose_name='특이사항')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='게시글')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
