# Generated by Django 4.2.4 on 2023-08-18 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="공고동물 이름")),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="공고동물 사진"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="공고동물 사진"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="공고동물 사진"
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("dog", "개"), ("cat", "고양이"), ("etc", "기타")],
                        default="미확인",
                        max_length=10,
                        verbose_name="동물",
                    ),
                ),
                (
                    "kind",
                    models.CharField(default="미확인", max_length=15, verbose_name="품종"),
                ),
                (
                    "weight",
                    models.CharField(default="미확인", max_length=10, verbose_name="몸무게"),
                ),
                (
                    "age",
                    models.CharField(default="미확인", max_length=10, verbose_name="나이"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("암컷", "암컷"), ("수컷", "수컷")],
                        default="미확인",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "is_neutered",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("중성화O", "중성화O"), ("중성화X", "중성화X")],
                        default="미확인",
                        max_length=11,
                        verbose_name="중성화",
                    ),
                ),
                (
                    "hashtags",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("1", "사람좋아"),
                            ("2", "순딩이"),
                            ("3", "사교적"),
                            ("4", "겁쟁이"),
                            ("5", "소심"),
                            ("6", "차분"),
                            ("7", "호기심"),
                            ("8", "애교쟁이"),
                            ("9", "몸짱"),
                            ("10", "집이좋아"),
                            ("11", "산책좋아"),
                            ("12", "먹보"),
                            ("13", "입짧음"),
                            ("14", "실내배변"),
                            ("15", "실외배변"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="한마디 없음", max_length=70, verbose_name="관리자 한마디"
                    ),
                ),
                ("alert", models.TextField(default="특이사항 없음", verbose_name="특이사항")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="작성일"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
