# Generated by Django 4.2.4 on 2023-08-18 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("입양", "입양"), ("재회", "재회")],
                        default="재회",
                        max_length=8,
                        verbose_name="카테고리 구분",
                    ),
                ),
                ("title", models.TextField(verbose_name="제목")),
                ("content", models.TextField(null=True, verbose_name="내용")),
                (
                    "image1",
                    models.ImageField(blank=True, upload_to="", verbose_name="사진(선택)"),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="사진(선택)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="작성일"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
