# Generated by Django 4.2.4 on 2023-08-18 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Found",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "found_date",
                    models.CharField(
                        max_length=15, verbose_name="실종 날짜 (ex:2023-08-11)"
                    ),
                ),
                ("found_place", models.TextField(verbose_name="실종 장소")),
                ("contact", models.TextField(verbose_name="연락처")),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("dog", "개"), ("cat", "고양이"), ("etc", "기타")],
                        default="unknown",
                        max_length=10,
                        verbose_name="동물 종류",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="품종"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("암컷", "암컷"), ("수컷", "수컷")],
                        default="미확인",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "is_neutered",
                    models.CharField(
                        choices=[("미확인", "미확인"), ("중성화O", "중성화O"), ("중성화X", "중성화X")],
                        default="미확인",
                        max_length=11,
                        verbose_name="중성화 여부",
                    ),
                ),
                (
                    "age",
                    models.CharField(default="미확인", max_length=10, verbose_name="나이"),
                ),
                (
                    "color",
                    models.CharField(default="미확인", max_length=15, verbose_name="털색"),
                ),
                ("title", models.TextField(verbose_name="제목")),
                ("content", models.TextField(null=True, verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="작성일"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, upload_to="", verbose_name="사진(필수)"),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="사진(선택)"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
    ]
